### PR TITLE
Fix new folder button focus and other improvements

### PR DESCRIPTION
**Pull request by pierotofy**
Fix the focus on the input for new folder dialog. Updates submodule.

### CODE REVIEW

**Comment by pierotofy** [comment]
Fixes renameDialog focus.

**Comment by pierotofy** [comment]
Added enter/esc keybindings.

**Comment by pierotofy** [comment]
Fix selection on toolbar. Toolbar buttons marked as selected did not remain selected.

@HeDo88TH make sure to look at this one so that you can understand how VueJS works. When you modified the Toolbar component, you moved `dataTools` away from `data()`, making it non-reactive.

**Comment by HeDo88TH** [comment]
> Fix selection on toolbar. Toolbar buttons marked as selected did not remain selected.
> 
> @HeDo88TH make sure to look at this one so that you can understand how VueJS works. When you modified the Toolbar component, you moved `dataTools` away from `data()`, making it non-reactive.

Ok. Is this still a draft or I can merge it?

**Comment by pierotofy** [comment]
Still draft, I'm still in the process of adding/fixing a few things.

**Comment by pierotofy** [comment]
Removed panels from Markdown component.

image


Ready for review @HeDo88TH 

Needs to be reviewed with https://github.com/DroneDB/CommonUI/pull/4

**Comment by HeDo88TH** [comment]
Nice 🚀

**Pull request merged**
