### PR TITLE
Potree

### PR DESCRIPTION
**Pull request by pierotofy**
Work in progress.

Related: https://github.com/DroneDB/CommonUI/pull/5
﻿

### CODE REVIEW

**Comment by pierotofy** [comment]
Proposed layout 
image

**Comment by pierotofy** [comment]
Done.

image

Now waiting for the EPT endpoint before this can be completed.

**Comment by pierotofy** [comment]
Done!

**Comment by HeDo88TH** [comment]
This is GOLD!

**Pull request merged**
