### PR TITLE
UI Changes

### PR DESCRIPTION
**Pull request by pierotofy**
Changes the UI to offer a more file system-centric approach.

### CODE REVIEW

**Comment by pierotofy** [comment]
Nexus files working.

image

**Comment by pierotofy** [comment]
Needs https://github.com/DroneDB/Registry/pull/247

**Comment by pierotofy** [comment]
Good to go @HeDo88TH

**Comment by pierotofy** [comment]
Closes https://github.com/DroneDB/DroneDB/issues/306

**Comment by HeDo88TH** [comment]
I tested it and it works amazing! I added a convenient button to potree/nexus to go back to the dataset.
If it's ok for you @pierotofy we can merge it!

**Comment by pierotofy** [comment]
Excellent, thanks!

**Pull request merged**
